INSERT INTO roles (id_rol, nombre) VALUES (1, 'Administrador');
INSERT INTO roles (id_rol, nombre) VALUES (2, 'Empleado');
INSERT INTO roles (id_rol, nombre) VALUES (3, 'Cajera');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (1, 'Estadísticas', 'ver');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (2, 'Estadísticas', 'crear');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (3, 'Eventos', 'ver');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (4, 'Eventos', 'crear');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (5, 'Eventos', 'modificar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (6, 'Eventos', 'eliminar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (7, 'Eventos', 'todos');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (8, 'Pedidos', 'ver');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (9, 'Pedidos', 'crear');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (10, 'Pedidos', 'modificar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (11, 'Pedidos', 'eliminar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (12, 'Pedidos', 'todos');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (13, 'Recetas', 'ver');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (14, 'Recetas', 'crear');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (15, 'Recetas', 'modificar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (16, 'Recetas', 'eliminar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (17, 'Recetas', 'todos');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (18, 'Productos', 'ver');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (19, 'Productos', 'crear');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (20, 'Productos', 'modificar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (21, 'Productos', 'eliminar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (22, 'Productos', 'todos');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (23, 'Proveedores', 'ver');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (24, 'Proveedores', 'crear');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (25, 'Proveedores', 'modificar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (26, 'Proveedores', 'eliminar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (27, 'Proveedores', 'todos');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (28, 'Stock', 'ver');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (29, 'Stock', 'crear');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (30, 'Stock', 'modificar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (31, 'Stock', 'eliminar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (32, 'Stock', 'todos');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (33, 'Agenda', 'ver');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (34, 'Agenda', 'crear');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (35, 'Agenda', 'modificar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (36, 'Agenda', 'eliminar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (37, 'Agenda', 'todos');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (38, 'Settings', 'ver');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (39, 'Insumos', 'ver');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (40, 'Insumos', 'crear');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (41, 'Insumos', 'modificar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (42, 'Insumos', 'eliminar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (43, 'Insumos', 'todos');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (44, 'Clientes', 'ver');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (45, 'Clientes', 'crear');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (46, 'Clientes', 'modificar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (47, 'Clientes', 'eliminar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (48, 'Clientes', 'todos');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (49, 'Sabores', 'ver');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (50, 'Sabores', 'crear');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (51, 'Sabores', 'modificar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (52, 'Sabores', 'eliminar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (53, 'Sabores', 'todos');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (54, 'Config. Empleados', 'ver');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (55, 'Config. Empleados', 'crear');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (56, 'Config. Empleados', 'modificar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (57, 'Config. Empleados', 'eliminar');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (58, 'Config. Empleados', 'todos');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (59, 'Notificaciones', 'ver');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (60, 'FuncionesUsuarios', 'ver');
INSERT INTO permisos (id_permiso, recurso, accion) VALUES (61, 'Acciones', 'ver');
-- Permisos para el rol Administrador (id_rol = 1)
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 1);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 2);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 3);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 4);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 5);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 6);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 7);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 8);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 9);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 10);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 11);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 12);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 13);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 14);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 15);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 16);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 17);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 18);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 19);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 20);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 21);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 22);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 23);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 24);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 25);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 26);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 27);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 28);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 29);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 30);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 31);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 32);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 33);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 34);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 35);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 36);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 37);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 38);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 39);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 40);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 41);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 42);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 43);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 44);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 45);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 46);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 47);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 48);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 49);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 50);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 51);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 52);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 53);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 54);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 55);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 56);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 57);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 58);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 59);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 60);
INSERT INTO rol_permiso (id_rol, id_permiso) VALUES (1, 61);
-- Cliente de prueba para demostración y testing
INSERT INTO clientes (dni, nombre, apellido, telefono, direccion, correo) VALUES ('99', 'Usuario', 'Generico', '123456789', 'Tucumán 123', 'usuario.generico@email.com');
